### ISSUE TITLE
希望能把内置host和自定义host功能加回来

### ISSUE THREAD

**Issue by BBplux** [FooIbar/EhViewer#104] opened 2023-10-27 03:36 UTC
### 复现步骤 / Step to reproduce

无

### 预期行为 / Expected behaviour

[Refine warning](https://github.com/FooIbar/EhViewer/commit/4f09de8a697c18e54757bb9ec550bdbc7842dc56) 
[Drop domain fronting and other network hacks since #1147 ](https://github.com/FooIbar/EhViewer/commit/2d20da70b8922e0b9988b007c31d970217691cb3)
[Drop custom hosts](https://github.com/FooIbar/EhViewer/commit/c112322daf8090d91d1e548cc34499e137444881)
内置host能直连，觉得还是很有必要的，希望能加回来来

### 实际行为 / Actual Behaviour

无

### EhViewer 版本号 / EhViewer version code

1.8.10.1

### EhViewer CI 版本 / EhViewer CI Version

null

### Android 系统版本 / Android version

null

### 设备型号 / Device model

null

### SoC 型号 / Soc model

null

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment] 2023-10-27 03:47
Duplicate of #12

**Closed by FooIbar** 2023-10-27 03:47 UTC
Labels: bug
