### ISSUE TITLE
突然无法访问里站

### ISSUE THREAD

**Issue by LPShigure** [FooIbar/EhViewer#1135] opened 2024-05-05 01:45 UTC
### 复现步骤 / Step to reproduce

![Screenshot_2024-05-05-09-24-16-570_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/86432985/1b8ff77b-2363-4c54-ba79-6e6641d38684)

### 预期行为 / Expected behaviour

其他版本eh浏览器都能访问

### 实际行为 / Actual Behaviour

![Screenshot_2024-05-05-09-24-16-570_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/86432985/7f4e2b86-063a-461e-9a9e-c5708146c929)

### 应用日志 / App logs

[log-2024-05-05-09-38-36-160.zip](https://github.com/FooIbar/EhViewer/files/15211456/log-2024-05-05-09-38-36-160.zip)

### 浏览站点 / Browsing site

ex-hentai

### EhViewer 版本号 / EhViewer version code

1.12

### EhViewer CI 版本 / EhViewer CI Version

13be4e4

### Android 系统版本 / Android version

xiaomi hyperos

### 设备型号 / Device model

mi10s

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [x] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment] 2024-05-05 01:47
Duplicate of #12

**Closed by FooIbar** 2024-05-05 01:47 UTC
Labels: bug
