### ISSUE TITLE
搜索运行过程中程序闪退

### ISSUE THREAD

**Issue by z1137** [FooIbar/EhViewer#1307] opened 2024-06-12 23:56 UTC
### 复现步骤 / Step to reproduce

在此过程中:
[https://github.com/FooIbar/EhViewer/issues/1306](url)
返回了桌面并再次切入后发生了闪退

### 预期行为 / Expected behaviour

正常

### 实际行为 / Actual Behaviour

闪退

### 应用日志 / App logs

[crash-2024-06-13-07-38-24-943.log](https://github.com/user-attachments/files/15812065/crash-2024-06-13-07-38-24-943.log)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.11.6-RC2

### EhViewer CI 版本 / EhViewer CI Version

70f4644

### Android 系统版本 / Android version

Magic OS 8.0

### 设备型号 / Device model

荣耀60

### SoC 型号 / Soc model

778G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment] 2024-06-13 11:28
Duplicate of #1302

**Closed by FooIbar** 2024-06-13 11:28 UTC
Labels: bug
