### ISSUE TITLE
缩略图无法加载

### ISSUE THREAD

**Issue by Sachielsun** [FooIbar/EhViewer#1531] opened 2024-08-18 02:49 UTC
### 复现步骤 / Step to reproduce

![Screenshot_2024-08-18-10-43-33-29_f2f1746601bf3b8](https://github.com/user-attachments/assets/e9ae0165-5bfa-4344-9dda-9b794d3ad914)

### 预期行为 / Expected behaviour

本身可以一直正常加载缩略图

### 实际行为 / Actual Behaviour
![Screenshot_2024-08-18-10-43-33-29_f2f1746601bf3b8](https://github.com/user-attachments/assets/800aedae-e76f-44cb-a397-5d8cda94c1ac)

最近打开发现无法加载缩略图

### 应用日志 / App logs

[log-2024-08-18-10-43-57-811.zip](https://github.com/user-attachments/files/16647043/log-2024-08-18-10-43-57-811.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.7

### EhViewer CI 版本 / EhViewer CI Version

7e1b3ab

### Android 系统版本 / Android version

coloros 14

### 设备型号 / Device model

oneplus 12

### SoC 型号 / Soc model

骁龙8

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by Sachielsun** [comment] 2024-08-18 04:03
抱歉未发现置顶，已解决

**Comment by FooIbar** [comment] 2024-08-18 06:55
Duplicate of #1529

**Closed by FooIbar** 2024-08-18 06:55 UTC
Labels: bug
