### ISSUE TITLE
The App crashes when open the EH

### ISSUE THREAD

**Issue by Mos-Py** [FooIbar/EhViewer#1680] opened 2024-09-25 09:13 UTC
### 复现步骤 / Step to reproduce

https://github.com/user-attachments/assets/64c56f9e-d9ec-40b3-9e4a-4f5d65eed67f

When I install and Log in account I cant open the EH

### 预期行为 / Expected behaviour

Don't the app crashes when I open EH

### 实际行为 / Actual Behaviour

When I log in Account I can't open EH when I open EH the app crashes//When I doesn't log in it won't crashes I don't know why
![image](https://github.com/user-attachments/assets/caacd7f1-811e-461a-be7e-e3316ee49a8a)

### 应用日志 / App logs

[logcat-2024-09-25-15-05-04-768.txt](https://github.com/user-attachments/files/17128042/logcat-2024-09-25-15-05-04-768.txt)
[2024-09-25-15-02-50-540.txt](https://github.com/user-attachments/files/17128043/2024-09-25-15-02-50-540.txt)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

6191ad7

### Android 系统版本 / Android version

ColorOS V12.1

### 设备型号 / Device model

Oppo Reno Ace

### SoC 型号 / Soc model

Qualcomm Snapdragon 855Plus Octa-core

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment] 2024-09-25 09:18
Duplicate of #1563

It has been fixed, you can enable "Use CI update channel" in Settings-About to update to the latest CI build.

**Closed by FooIbar** 2024-09-25 09:18 UTC
Labels: bug
