### ISSUE TITLE
无法加载

### ISSUE THREAD

**Issue by HuaJi2333DaDa** [FooIbar/EhViewer#276] opened 2023-11-16 00:27 UTC
### 复现步骤 / Step to reproduce

0. 重装
1. 启动
2. 登录
3. 复现
4. 

https://github.com/FooIbar/EhViewer/assets/30079825/e15eb91d-7a3e-4b45-a5a9-184cfec3840b

### 预期行为 / Expected behaviour

它应该正常显示画廊

### 实际行为 / Actual Behaviour

![Screenshot_2023-11-16-08-00-17-837_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/30079825/cb707156-d0ee-4c93-bc98-074634f0d499)

### 应用日志 / App logs

[log-2023-11-16-08-21-29-584.zip](https://github.com/FooIbar/EhViewer/files/13370909/log-2023-11-16-08-21-29-584.zip)

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.8.12.0-SNAPSHOT-gms

### EhViewer CI 版本 / EhViewer CI Version

b63b36e

### Android 系统版本 / Android version

HyperOS 1.0.23.11.8.DEV / Android 14

### 设备型号 / Device model

Redmi K60 Pro

### SoC 型号 / Soc model

高通骁龙 8 Gen 2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment] 2023-11-16 01:45
Duplicate of #12

**Closed by FooIbar** 2023-11-16 01:45 UTC
Labels: bug
