### ISSUE TITLE
屏蔽列表删除内容闪退

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#130] opened 2023-10-29 02:58 UTC
### 复现步骤 / Step to reproduce

https://github.com/FooIbar/EhViewer/assets/88327304/3e73b23b-8478-4906-bcd6-bdeada7cdd77

### 预期行为 / Expected behaviour

正常删除

### 实际行为 / Actual Behaviour

闪退

### 应用日志 / App logs

[crash-2023-10-29-10-49-51-124.log](https://github.com/FooIbar/EhViewer/files/13197083/crash-2023-10-29-10-49-51-124.log)

### 备注 / Addition details

前面可以正常删除，快速删除数个后，以后删除均会闪退。

### EhViewer 版本号 / EhViewer version code

1.8.11.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

e2f024a

### Android 系统版本 / Android version

HarmonyOS 4.0.0.116

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment] 2023-10-29 04:26
Duplicate of #126

**Closed** 2023-10-29 07:56 UTC
Labels: bug

**Comment by tmby** [comment] 2023-10-29 09:45
https://github.com/FooIbar/EhViewer/assets/88327304/c3afbd38-f9b7-47fd-bcff-a66fc15030d6

还是闪退
![crash-2023-10-29-17-41-46-397.zip](https://github.com/FooIbar/EhViewer/files/13197716/crash-2023-10-29-17-41-46-397.zip)

**Comment by FooIbar** [comment] 2023-10-30 19:32
Fixed by #154
