### ISSUE TITLE
安装后出现错误界面，更新前后都不能使用

### ISSUE THREAD

**Issue by nonono173** [FooIbar/EhViewer#1472] opened 2024-07-30 03:30 UTC
### 复现步骤 / Step to reproduce

https://github.com/user-attachments/assets/bf17cec2-69a0-402c-b1ca-74eea1878b5f

### 预期行为 / Expected behaviour

正常打开

### 实际行为 / Actual Behaviour

![Screenshot_20240730_111436](https://github.com/user-attachments/assets/36d7f5f6-6ec3-49ef-8c8f-c9c72730b9a0)

### 应用日志 / App logs

无

### 备注 / Addition details

1.11.7版本新出现了这种情况
![Screenshot_20240730_111431](https://github.com/user-attachments/assets/bbdea8c7-d70f-40ba-adc9-071a86d109b4)

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.11.7

### EhViewer CI 版本 / EhViewer CI Version

最新

### Android 系统版本 / Android version

PD2324F_A_14.0.23.6.W10.V000L1

### 设备型号 / Device model

vivo X100 Pro

### SoC 型号 / Soc model

3.25GHz天玑9300八核处理器

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment] 2024-07-30 04:49
Duplicate of #12

**Closed by FooIbar** 2024-07-30 04:49 UTC
Labels: bug
