### ISSUE TITLE
应用搜索栏和系统状态栏图标重叠

### ISSUE THREAD

**Issue by VVaraiotoko** [FooIbar/EhViewer#86] opened 2023-10-25 01:01 UTC
### 复现步骤 / Step to reproduce

安装导航抽屉迁移到compose的版本即出现

### 预期行为 / Expected behaviour

它应该不重叠

### 实际行为 / Actual Behaviour

实际上重叠了
![Screenshot_20231025-084927](https://github.com/FooIbar/EhViewer/assets/28192782/065a62e5-165c-49da-a86a-ff834827adb8)

### EhViewer 版本号 / EhViewer version code

1.8.11.0-snapshot-gms

### EhViewer CI 版本 / EhViewer CI Version

5784eb0

### Android 系统版本 / Android version

Android 13, Stock ROM 67.0.A.4.104

### 设备型号 / Device model

Sony Xperia 1 V

### SoC 型号 / Soc model

骁龙8 GEN 2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment] 2023-10-25 04:41
Duplicate of #84

**Closed** 2023-10-25 15:51 UTC
Labels: bug
