### ISSUE TITLE
更新新c之后Image Size Settings设置了无数次1280一会就回变回atuo是780的状态

### ISSUE THREAD

**Issue by TY12354** [FooIbar/EhViewer#1821] opened 2024-10-28 08:58 UTC
### 复现步骤 / Step to reproduce

设置1280x点击apply退出再次点击设置还是atuo

### 预期行为 / Expected behaviour

变成1280x

### 实际行为 / Actual Behaviour

变回atuo

### 应用日志 / App logs

[log-2024-10-28-16-55-57-620.zip](https://github.com/user-attachments/files/17539905/log-2024-10-28-16-55-57-620.zip)

### 浏览站点 / Browsing site

ex

### EhViewer 版本号 / EhViewer version code

1.13.0

### EhViewer CI 版本 / EhViewer CI Version

snapshot

### Android 系统版本 / Android version

miui13.0.10

### 设备型号 / Device model

红米k50

### SoC 型号 / Soc model

8+1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment] 2024-10-28 09:01
Duplicate of #137 

在高级设置中开启桌面版网站后会使用 1280x 作为默认分辨率

**Closed by FooIbar** 2024-10-28 09:01 UTC
Labels: bug
