### ISSUE TITLE
Swiping right cannot bring up the quick search bar

### ISSUE THREAD

**Issue by akinokoika** [FooIbar/EhViewer#116] opened 2023-10-27 23:34 UTC
### 复现步骤 / Step to reproduce

Fresh install
Swiping right
No reaction

### 预期行为 / Expected behaviour

Bring up the quick search bar

### 实际行为 / Actual Behaviour

No reaction

### 应用日志 / App logs

--------- beginning of crash
10-17 07:44:25.824  8991  8991 E AndroidRuntime: FATAL EXCEPTION: main
10-17 07:44:25.824  8991  8991 E AndroidRuntime: Process: moe.tarsin.ehviewer, PID: 8991
10-17 07:44:25.824  8991  8991 E AndroidRuntime: java.lang.RuntimeException: java.lang.NoSuchMethodException: Yo0.values []
10-17 07:44:25.824  8991  8991 E AndroidRuntime: 	at java.lang.Enum.enumValues(Enum.java:270)

### 备注 / Addition details

If this is not a bug but a feature that is not implemented, can you update this feature in the future?

### EhViewer 版本号 / EhViewer version code

1.8.10.2

### EhViewer CI 版本 / EhViewer CI Version

10c7019

### Android 系统版本 / Android version

Android 11

### 设备型号 / Device model

Aquos sense

### SoC 型号 / Soc model

Qualcomm Snapdragon 690

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment] 2023-10-28 03:13
Works as intended, may be changed in the future.
I'll close this for now, but will ping you if there are any updates.

**Closed by FooIbar** 2023-10-28 03:13 UTC
Labels: bug
